# Generated by Django 5.0.4 on 2024-05-01 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=20, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('contraseña', models.CharField(max_length=30)),
            ],
        ),
    ]
