# Generated by Django 5.0.4 on 2024-05-01 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='residents',
            fields=[
                ('identificacion', models.IntegerField(primary_key=45, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('edificio', models.CharField(blank=True, max_length=10, null=True)),
                ('apartamento', models.CharField(max_length=10)),
                ('cara', models.FileField(upload_to='archivos/')),
                ('apellido', models.CharField(max_length=80)),
            ],
        ),
    ]
